theme: jekyll-theme-slate
title: Pedro Almeida
description: University Courses

# About/contact
author:
  name:       Pedro Almeida
  url:        http://www.ptalmeida.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
